AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layer providing sharp with HEIC support

Parameters:
  OrganizationId:
    Default: none
    Description:
      With the principal set to *, grant permission to all accounts in the
      specified organization.
    Type: String
  Principal:
    Default: account
    Description:
      An account ID, or * to grant permission to use the layer to all AWS
      accounts.
    Type: String
  LayerName:
    Default: sharp-heic
    Description: The name of the Lambda Layer that will be created.
    Type: String

Conditions:
  NoOrganizationId: !Equals [!Ref OrganizationId, none]
  UseDefaultPrincipal: !Equals [!Ref Principal, account]

Resources:
  SharpHEICLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Sharp Layer with HEIC Support
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
        - nodejs20.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  SharpHEICLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref SharpHEICLayer
      Principal:
        Fn::If:
          - UseDefaultPrincipal
          - !Ref AWS::AccountId
          - !Ref Principal
      OrganizationId:
        Fn::If:
          - NoOrganizationId
          - !Ref AWS::NoValue
          - !Ref OrganizationId

Outputs:
  SharpHEICLayerArn:
    Value: !Ref SharpHEICLayer
    Description: ARN of the Sharp HEIC Lambda Layer
    Export:
      Name: SharpHEICLayerArn
